apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-demo-cert
  namespace: otel
spec:
  secretName: otel-demo-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - otel-demo.local
