ingress:
  enabled: true
  host: demo.local
  tls:
    enabled: true
    secretName: otel-demo-tls
  services:
    - name: frontend
      path: /frontend
      port: 80
    - name: cartservice
      path: /cart
      port: 80
    - name: checkoutservice
      path: /checkout
      port: 80
    - name: currencyservice
      path: /currency
      port: 80
    - name: productcatalogservice
      path: /product
      port: 80
    - name: recommendationservice
      path: /recommendation
      port: 80
    - name: shippingservice
      path: /shipping
      port: 80
    - name: adservice
      path: /ads
      port: 80
