apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-demo
  namespace: otel-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: otel-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
