apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-frontend-ingress
  namespace: otel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - demo.local
      secretName: otel-demo-tls
  rules:
    - host: demo.local
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
